# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  twitter_public_api_key: Fz5GAExsJSPmZMXtJEmFLa1NX
  twitter_public_api_secret: nQNWiVdwHbRMStXqLyQ0Us3CyMBcYhQgCb3BStHlC3nR2jOfF5
  twitter_secret_api_key: ONiJPLUo0djzsftlgah0jlBzV
  twitter_secret_api_secret: 8UM1WipxPq2ySsOYuJxgNaXPEVKiJl8RMP5JelsheGxhZ0t5kV
  twitter_secret_access_token: 637192024-gII9EgC2eUAAPn2lRS0OQsUG531V0gcKwAjycoPg
  twitter_secret_access_secret: FInT2mLXA6aAHdKXL1IOvn8Jo0bUJziPsYf8jsR2u3BBf
  secret_key_base: 86e08ceccca689f5c2f0c6c97df0b3e2739be01f509b704266950dbfc932633d2b50ea2622ccc6ddc61d6ec1f44d9c88dd7dfe9a74a5df32dc2127569fa0ab30

test:
  secret_key_base: b9fc78c64f18ae3b5a39f907f6279b35c7ff69d90a29ab9cbece84469342de4a972711931b1a99c72f6bdb7e6b9cd1b4a15d86c681f4179c8a865c89b7ec80a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  twitter_public_api_key: <%= ENV["TWITTER_PUBLIC_API_KEY"] %>
  twitter_public_api_secret: <%= ENV["TWITTER_PUBLIC_API_SECRET"] %>
  twitter_secret_api_key: <%= ENV["TWITTER_SECRET_API_KEY"] %>
  twitter_secret_api_secret: <%= ENV["TWITTER_SECRET_API_SECRET"] %>
  twitter_secret_access_token: <%= ENV["TWITTER_SECRET_ACCESS_TOKEN"] %>
  twitter_secret_access_secret: <%= ENV["TWITTER_SECRET_ACCESS_SECRET"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
