# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  twitter_public_api_key: Fz5GAExsJSPmZMXtJEmFLa1NX
  twitter_public_api_secret: nQNWiVdwHbRMStXqLyQ0Us3CyMBcYhQgCb3BStHlC3nR2jOfF5
  secret_key_base: 86e08ceccca689f5c2f0c6c97df0b3e2739be01f509b704266950dbfc932633d2b50ea2622ccc6ddc61d6ec1f44d9c88dd7dfe9a74a5df32dc2127569fa0ab30
  wuxi_api_url: "http://localhost:3788/api"
  wuxi_api_token: 62791a99c5c7ff6c8a879b35c7ff69b35c7

test:
  secret_key_base: b9fc78c64f18ae3b5a39f907f6279b35c7ff69d90a29ab9cbece84469342de4a972711931b1a99c72f6bdb7e6b9cd1b4a15d86c681f4179c8a865c89b7ec80a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  twitter_public_api_key: <%= ENV["TWITTER_PUBLIC_API_KEY"] %>
  twitter_public_api_secret: <%= ENV["TWITTER_PUBLIC_API_SECRET"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  wuxi_api_url: "http://wuxi.shiriculapo.com/api"
  wuxi_api_token: <%= ENV["WUXI_API_TOKEN"] %>
